CREATE TABLE `Movie2Director` (
  `MOVIE_ID` int(11) NOT NULL,
  `DIRECTOR_ID` int(11) NOT NULL,
  PRIMARY KEY (`MOVIE_ID`,`DIRECTOR_ID`),
  KEY `FK_Movie2Director_DIRECTOR_ID` (`DIRECTOR_ID`),
  CONSTRAINT `FK_Movie2Director_DIRECTOR_ID` FOREIGN KEY (`DIRECTOR_ID`) REFERENCES `PERSON` (`ID`),
  CONSTRAINT `FK_Movie2Director_MOVIE_ID` FOREIGN KEY (`MOVIE_ID`) REFERENCES `MOVIE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
