CREATE TABLE `Movie2Actor` (
  `ACTOR_ID` int(11) NOT NULL,
  `MOVIE_ID` int(11) NOT NULL,
  PRIMARY KEY (`ACTOR_ID`,`MOVIE_ID`),
  KEY `FK_Movie2Actor_MOVIE_ID` (`MOVIE_ID`),
  CONSTRAINT `FK_Movie2Actor_ACTOR_ID` FOREIGN KEY (`ACTOR_ID`) REFERENCES `PERSON` (`ID`),
  CONSTRAINT `FK_Movie2Actor_MOVIE_ID` FOREIGN KEY (`MOVIE_ID`) REFERENCES `MOVIE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
